---
- name: Create Webserver
  hosts: webservers

  tasks:
    - name: Install Packages
      dnf: 
        name:
          - httpd
          - firewalld
        state: present

    - name: Enable serivces
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: Add firewall Rule
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
